name: Cargo Bump Version
on: 
  workflow_dispatch: {}  # Allows manual trigger from GitHub Actions UI
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 2 AM UTC

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@main
        with:
          token: ${{ secrets.PAT }}  # Use a Personal Access Token to push changes

      - name: Install toml-cli (for version manipulation)
        run: cargo install toml-cli || true

      - name: Bump Cargo Versions Manually
        run: |
          for folder in dexios dexios-gui dexios-core dexios-domain; do
            cargo_toml="$folder/Cargo.toml"
            if [ -f "$cargo_toml" ]; then
              echo "Bumping version in $cargo_toml"
              current_version=$(toml get --raw "$cargo_toml" package.version)
              new_version=$(echo "$current_version" | awk -F. '{print $1"."$2"."$3+1}')
              toml set "$cargo_toml" package.version "$new_version"
            else
              echo "Skipping $cargo_toml (file not found)"
            fi
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Bump Cargo versions" || echo "No changes to commit"
          git push origin HEAD || echo "No changes to push"
