name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - windows-latest
          - macos-latest
        rust:
          - 1.81.0 # The MSRV
          - stable
          - beta
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Restore cargo cache
        uses: actions/cache@v4.0.2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ matrix.rust }}-${{ hashFiles('Cargo.lock') }}

      - name: Run tests
        uses: actions-rs/cargo@v1.0.3
        with:
          command: test
          args: --all-features --release --verbose
